<a href="https://colab.research.google.com/github/lenavyakulina/ML22/blob/main/%D0%A0%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F_%D0%92%D1%8F%D0%BA%D1%83%D0%BB%D0%B8%D0%BD%D0%B0_121%D0%9C_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# 13.1 Подгонка прямой
# Задача № 1: требуется натренировать модель, представляющую линейную связь между признаком и вектором целей
# Решение: использовать линейную регрессию (в библиотеке scikit-leam это класс LinearRegression):
# Загрузить библиотеки
from sklearn.linear_model import LinearRegression 
from sklearn.datasets import load_boston

In [ ]:
# Загрузить данные только с двумя признаками
boston = load_boston()
features = boston.data[:,0:2] 
target = boston.target

In [10]:
# Создать объект линейной регрессии
regression = LinearRegression()

In [12]:
# Выполнить подгонку линейной регресии
model = regression.fit(features,  target)

In [13]:
# Взглянуть на точку пересечения
model.intercept_

22.485628113468223

In [14]:
# Взглянуть на коэффициенты признаков
model.coef_

array([-0.35207832,  0.11610909])

In [15]:
# Первое значение в векторе целей,умноженное на 1000
target[0]*1000

24000.0

In [16]:
# Предсказать целевое значение первого наблюдения, умноженное на 1000 
model.predict(features)[0]*1000
# Наша модель сместилась всего на $573.4

24573.366631705547

In [17]:
# Первый коэффициент, умноженный на 1000 
model.coef_[0]*1000
# Это говорит о том, что каждое преступление на душу населения снизит цену дома примерно на $352

-352.07831564026765

In [ ]:
# 13.2 Обработка интерактивных эффектов
# Задача № 2: Имеется признак, влияние которого на целевую переменную зависит от другого признака.
# Решение : Создать член взаимодействия для захвата этой зависимости с помощью объекта класса PolynomialFeatures библиотеки scikit-leam:
# Загрузить библиотеки
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures
# Загрузить данные только с двумя признаками 
boston = load_boston()
features = boston.data[:,0:2] 
target = boston.target
# Создать член, характеризующий взаимодействие между признаками 
interaction = PolynomialFeatures(
degree=3, include_bias=False, interaction_only=True) 
features_interaction = interaction.fit_transform(features)
# Создать объект линейной регрессии 
regression = LinearRegression()
# Выполнить подгонку линейной регрессии
model = regression.fit(features_interaction, target)

In [19]:
# Взглянуть на признаки для первого наблюдения 
features[0]

array([6.32e-03, 1.80e+01])

In [20]:
# Импортировать библиотеку 
import numpy as np
# Для каждого наблюдения перемножить значения первого и второго признаков
interaction_term = np.multiply(features[:, 0], features[:, 1])
# Взглянуть на член взаимодействия для первого наблюдения 
interaction_term[0]

0.11376

In [21]:
# Взглянуть на значения для первого наблюдения 
features_interaction[0]

array([6.3200e-03, 1.8000e+01, 1.1376e-01])

In [ ]:
# 13.3 Подгонка нелинейной связи
# Задача № 3: Требуется смоделировать нелинейную связь.
# Решение: Создать полиномиальную регрессию путем включения полиномиальных признаков в линейную регрессионную модель:
# Загрузить библиотеки
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures
# Загрузить данные с одним признаком 
boston = load_boston()
features = boston.data[:,0:1] 
target = boston.target
# Создать полиномиальные признаки х^2 и х^3
polynomial = PolynomialFeatures(degree=3, include_bias=False) 
features_polynomial = polynomial.fit_transform(features)
# Создать объект линейной регрессии 
regression = LinearRegression()
# Выполнить подгонку линейной регрессии
model = regression.fit(features_polynomial, target)

In [26]:
# Взглянуть на первое наблюдение 
features[0]

array([0.00632])

In [27]:
# Взглянуть на первое наблюдение, возведенное во вторую степень, х^2 
features[0]**2

array([3.99424e-05])

In [28]:
# Взглянуть на первое наблюдение, возведенное в третью степень, х^3 
features[0]**3

array([2.52435968e-07])

In [29]:
# Взглянуть на значения первого наблюдения для х, х^2 и х^3 
features_polynomial[0]

array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

In [ ]:
# 13.4.  Снижение дисперсии с помощью регуляризации
# Задача № 4: Требуется уменьшить дисперсию линейной регрессионной модели.
# Решение : Использовать обучающийся алгоритм, который включает сжимающий штраф (так называемую регуляризацию), такой как гребневая регрессия и лассо-регрессия:
# Загрузить библиотеки
from sklearn.linear_model import Ridge
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler
# Загрузить данные 
boston = load_boston() 
features = boston.data 
target = boston.target
# Стандартизировать признаки 
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)
# Создать объект гребневой регрессии со значением альфа 
regression = Ridge(alpha=0.5)
# Выполнить подгонку линейной регрессии
model = regression.fit(features_standardized, target)

In [32]:
# Загрузить библиотеку
from sklearn.linear_model import RidgeCV
# Создать объект гребневой регрессии с тремя значениями alpha 
regr_cv = RidgeCV(alphas=[0.1, 1.0, 10.0])
# Выполнить подгонку линейной регрессии
model_cv = regr_cv.fit(features_standardized, target)
# Взглянуть на коэффициенты 
model_cv.coef_

array([-0.91987132,  1.06646104,  0.11738487,  0.68512693, -2.02901013,
        2.68275376,  0.01315848, -3.07733968,  2.59153764, -2.0105579 ,
       -2.05238455,  0.84884839, -3.73066646])

In [33]:
# Взглянуть на alpha 
model_cv.alpha_

1.0

In [ ]:
# 13.5. Уменьшение количества признаков с помощью лассо-регрессии
# Задача № 5 : Требуется упростить линейную регрессионную модель, уменьшив количество признаков.
# Решение : Использовать лассо-регрессию:
# Загрузить библиотеки
from sklearn.linear_model import Lasso
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler
# Загрузить данные 
boston = load_boston() 
features = boston.data 
target = boston.target
# Стандартизировать признаки 
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)
# Создать объект лассо-регрессии со значением alpha 
regression = Lasso(alpha=0.5)
# Выполнить подгонку линейной регрессии
model = regression.fit(features_standardized, target)

In [35]:
# Взглянуть на коэффициенты 
model.coef_


array([-0.11526463,  0.        , -0.        ,  0.39707879, -0.        ,
        2.97425861, -0.        , -0.17056942, -0.        , -0.        ,
       -1.59844856,  0.54313871, -3.66614361])

In [36]:
# Создать лассо-регрессию с высоким alpha 
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized,  target) 
model_a10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])